In [5]:
import numpy as np 
a = np.array([[1,2],[1,-1]])
b = np.array([[2,-3],[-4,1]])
ab = a.dot(b)
ba = b.dot(a)
c = ab - ba
print(c)

[[-5 -8]
 [ 9  5]]


In [6]:
a = np.array([[-1,2],[0,1]])
a_2 = np.linalg.matrix_power(a, 2)
print(a_2)

[[1 0]
 [0 1]]


In [7]:
a = np.array([[3,5],[6,-1]])
b = np.array([[2,1],[-3,2]])
c = a.dot(b) 
print(c)

[[-9 13]
 [15  4]]


In [8]:
a = np.matrix('2 3 4; 1 0 6; 7 8 9') 
det = np.linalg.det(a)
print("Визначник = ", det.round(1))

Визначник =  35.0


In [9]:
a = np.matrix('1 2 3 4;-2 1 -4 3; 3 -4 -1 2; 4 3 -2 -1')
det = np.linalg.det(a)
print("Визначник = ", det.round(1))

Визначник =  900.0


In [10]:
a = np.array([[1,2,-3],[0,1,2],[0,0,1]])
inv = np.linalg.inv(a)
print('Обернена матриця : ',"\n", inv)

Обернена матриця :  
 [[ 1. -2.  7.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]]


In [11]:
a = np.array([[1,2,3,4],[3,-1,2,5],[1,2,3,4],[1,3,4,5]])
rank_a = np.linalg.matrix_rank(a)
print(rank_a)

2


In [12]:
a = np.array([[1,2,-1],[3,4,1],[5,1,-3]])
b = np.array([[-3],[1],[-2]])
def kram(a,b):# метод Крамера
    det_a = np.linalg.det(a)
    if det_a != 0:
       a1 = np.matrix(a)
       a2 = np.matrix(a)
       a3 = np.matrix(a)
       a1[:, 0] = b
       a2[:, 1] = b
       a3[:, 2] = b
       x = np.linalg.det(a1)/det_a
       y =np.linalg.det(a2)/det_a
       z= np.linalg.det(a3)/det_a
       # print('Solving a system of linear algebraic equations by Cramer*s method')
       print('x=',x.round(1),'y=',y.round(1),'z=',z.round(1)) 
    else:
        print("Система немає розв'язків, оскільки визначник дорівнює 0 ")
    return(x,y,z)
kram(a,b)
print("Перевірка розв'язку : ","\n", np.linalg.solve(a,b).round(1))


x= 1.0 y= -1.0 z= 2.0
Перевірка розв'язку :  
 [[ 1.]
 [-1.]
 [ 2.]]


In [13]:
a = np.array([[1,2,-1],[3,4,1],[5,1,-3]])
b = np.array([[-3],[1],[-2]])
inv_a = np.linalg.inv(a)
x = inv_a.dot(b)
print('X=', x)
print("Перевірка розв'язання : ","\n", np.linalg.solve(a,b).round(1))

X= [[ 1.]
 [-1.]
 [ 2.]]
Перевірка розв'язання :  
 [[ 1.]
 [-1.]
 [ 2.]]


In [18]:
import random as rd
n = 3
m = 4
a = np.zeros((n, m), dtype=int)
for i in range(n): 
    for j in range(m):
        a[i][j] = rd.randint(-20, 20)

print(a)

for i in range(n): 
    counter_row = 0
    for j in range(m):
        if(a[i][j] < 0):
            counter_row += 1
    print(f"Кількість від'ємних елементів {i+1} рядка: {counter_row}")

for j in range(m): 
    counter_column = 0
    for i in range(n):
        if(a[i][j] < 0):
            counter_column += 1
    print(f"Кількість від'ємних елементів {j+1} стовпця: {counter_column}")


[[  1   1 -15  13]
 [ 10   7  -1 -18]
 [ 15   3  -6  15]]
Кількість від'ємних елементів 1 рядка: 1
Кількість від'ємних елементів 2 рядка: 2
Кількість від'ємних елементів 3 рядка: 1
Кількість від'ємних елементів 1 стовпця: 0
Кількість від'ємних елементів 2 стовпця: 0
Кількість від'ємних елементів 3 стовпця: 3
Кількість від'ємних елементів 4 стовпця: 1
